### PR TITLE
first pandora run and type

### PR DESCRIPTION
**Pull request by WilliamDelamare**
Change int to float in order to avoid cast exception

Also added a print for unhandheld exceptions

### CODE REVIEW

**Comment by dhmmasson** [comment]
Nice idea of using an option for using the debug. 
could we use `--debug` and `-d`

**Comment by dhmmasson** [comment]
I made some modification, I have trouble pushing it to github right now
Will do in the afternoon

**Comment by dhmmasson** [comment]
@WilliamDelamare Before merging can you try it, on your side ?
There is still a group to create tomorrow. that'd be nice have it roll out before that.

**Comment by WilliamDelamare** [comment]
Test ok:
* Added a division by zero
* No message without `-d` option except "ERROR: Unhandled error"
* Additional information with `-d` option
image

No changes in MultiTest.java (i.e., no extra `-d` options in the command line) as the checked output is based on stdout, not stderr.

**Pull request merged**
